[package]
name = "harmony_rust_sdk"
version = "0.1.0"
authors = [ "Yusuf Bera Ertan <y.bera003.06@protonmail.com>" ]
edition = "2018"
license = "MIT"
description = "Rust library to work with the Harmony chat protocol."
repository = "https://github.com/yusdacra/harmony_rust_sdk"
homepage = "https://github.com/yusdacra/harmony_rust_sdk"
keywords = [ "harmony", "protocol", "api", "client" ]
categories = [ "api-bindings" ]
exclude = [
	"*.nix",
	"flake.lock",
	".github/*",
]

[dependencies]
prost = "0.6"
prost-types = "0.6"
tonic = { version = "0.3", features = [ "tls", "tls-roots", "prost" ] }

log = { version = "0.4", optional = true }
http = { version = "0.2", optional = true }
assign = { version = "1.1", optional = true }
paste = { version = "1.0", optional = true }
futures-util = { version = "0.3", optional = true }
reqwest = { version = "0.10", default-features = false, features = [ "rustls-tls-native-roots" ], optional = true }

parking_lot = { version = "0.11", optional = true }

[build-dependencies]
tonic-build = "0.3"

[features]
default = [ ]
client = [ "gen_client", "futures-util", "paste", "assign", "http", "log", "reqwest" ]
gen_client = [ ]
gen_server = [ ]

use_parking_lot = [ "parking_lot" ]

[dev-dependencies]
tokio = { version = "0.2", features = [ "rt-threaded", "macros", "fs" ] }
env_logger = "0.8"

[[test]]
name = "all"
required-features = [ "client" ]

[[example]]
name = "echo_bot"
required-features = [ "client" ]

[[example]]
name = "message_log"
required-features = [ "client" ]
