[package]
name = "harmony_rust_sdk"
version = "0.1.0"
authors = ["Yusuf Bera Ertan <y.bera003.06@protonmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
prost = { git = "https://github.com/danburkert/prost.git" }
prost-types = { git = "https://github.com/danburkert/prost.git" }
bytes = "0.6"

[build-dependencies]
prost-build = { git = "https://github.com/danburkert/prost.git" }
