[package]
name = "harmony_rust_sdk"
version = "0.5.2"
authors = ["Yusuf Bera Ertan <y.bera003.06@protonmail.com>"]
edition = "2018"
license = "MIT"
description = "Rust library to work with the Harmony chat protocol."
repository = "https://github.com/harmony-development/harmony_rust_sdk"
homepage = "https://github.com/harmony-development/harmony_rust_sdk"
keywords = ["harmony", "protocol", "api", "chat", "client"]
categories = ["api-bindings"]
exclude = ["*.nix", "flake.lock", ".github/*"]

[workspace]
members = ["harmony_derive"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
prost = "0.7"
prost-types = "0.7"
derive-new = "0.5"
derive_more = "0.99"
hrpc = { version = "0.8", default-features = false }

harmony_derive = { version = "0.1.2", path = "harmony_derive", optional = true }
reqwest = { version = "0.11", default-features = false, features = [
	"rustls-tls-native-roots",
	"json",
	"multipart",
], optional = true }
async-trait = { version = "0.1.48", optional = true }
tracing = { version = "0.1", optional = true }
paste = { version = "1.0", optional = true }
futures = { version = "0.3", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
tokio = { version = "1.6", features = ["sync"], optional = true }

urlencoding = { version = "1.1", optional = true }
http = "0.2"

parking_lot = { version = "0.11", optional = true }

[build-dependencies]
hrpc-build = { version = "0.5", default-features = false, features = ["rustfmt"] }

[features]
default = [
	"gen_chat",
	"gen_auth",
	"gen_mediaproxy",
	"gen_voice",
	"gen_harmonytypes",
]
client = [
	"gen_chat",
	"gen_auth",
	"gen_mediaproxy",
	"gen_voice",
	"gen_harmonytypes",
	"gen_client",
	"reqwest",
	"serde",
	"tokio",
	"futures",
	"paste",
	"tracing",
	"urlencoding",
]
request_method = ["async-trait"]
gen_client = ["hrpc/client", "hrpc-build/client"]
gen_server = ["hrpc/server", "hrpc-build/server"]

gen_chat = ["gen_harmonytypes", "harmony_derive"]
gen_auth = []
gen_mediaproxy = ["gen_harmonytypes"]
gen_voice = []
gen_harmonytypes = []

[dev-dependencies]
tokio = { version = "1.6.0", features = ["rt", "macros", "fs"] }
env_logger = "0.8"
ctrlc = "3.1.8"

[[test]]
name = "all"
required-features = ["client"]

[[example]]
name = "echo_bot"
required-features = ["client"]

[[example]]
name = "message_log"
required-features = ["client"]

[[example]]
name = "cmd_bot"
required-features = ["client"]

[package.metadata.nix]
build = true
library = true

[workspace.metadata.nix]
systems = ["x86_64-linux"]
