[package]
name = "harmony_rust_sdk"
version = "0.6.1"
authors = ["Yusuf Bera Ertan <y.bera003.06@protonmail.com>"]
edition = "2021"
license = "MIT"
description = "Rust library to work with the Harmony chat protocol."
repository = "https://github.com/harmony-development/harmony_rust_sdk"
homepage = "https://github.com/harmony-development/harmony_rust_sdk"
keywords = ["harmony", "protocol", "api", "chat", "client"]
categories = ["api-bindings"]
exclude = ["*.nix", "flake.lock", ".github/*"]

[workspace]
members = ["harmony_derive"]
resolver = "2"

[package.metadata.docs.rs]
all-features = true

[dependencies]
prost = "0.9"
derive-new = "0.5"
derive_more = "0.99"
hrpc = { version="0.26", default-features=false }

harmony_derive = { version="0.1.2", path="harmony_derive", optional=true }
reqwest = { version="0.11", default-features=false, features=[
	"rustls-tls-native-roots",
	"json",
	"multipart",
], optional=true }
tracing = { version="0.1", optional=true }
paste = { version="1.0", optional=true }
serde = { version="1.0", features=["derive"] }
tokio = { version="1.9", features=["sync", "parking_lot"], optional=true }

urlencoding = { version="2.1", optional=true }
http = "0.2"
parking_lot = "0.11"
rkyv = { version="0.7", optional=true }

[build-dependencies]
hrpc-build = { version="0.26", default-features=false }
prost-build = "0.9"
regex = "1"
walkdir = "2"

[features]
default = [
	"gen_chat",
	"gen_auth",
	"gen_mediaproxy",
	"gen_voice",
	"gen_harmonytypes",
	"gen_sync",
	"gen_batch",
	"gen_profile",
	"gen_emote",
]
client = [
	"gen_chat",
	"gen_auth",
	"gen_mediaproxy",
	"gen_voice",
	"gen_harmonytypes",
	"gen_client",
	"reqwest",
	"tokio",
	"paste",
	"tracing",
	"urlencoding",
	"harmony_derive/client",
]
gen_client = ["hrpc/client", "hrpc-build/client"]
gen_server = ["hrpc/server", "hrpc-build/server"]

gen_chat = ["gen_harmonytypes", "gen_profile", "gen_emote", "harmony_derive"]
gen_auth = []
gen_mediaproxy = ["gen_harmonytypes"]
gen_voice = []
gen_harmonytypes = []
gen_sync = []
gen_batch = []
gen_profile = []
gen_emote = []

[dev-dependencies]
tokio = { version="1.9", features=["rt", "macros", "fs"] }
tracing-subscriber = "0.2"
ctrlc = "3.1.8"

[[example]]
name = "echo_bot"
required-features = ["client"]

[[example]]
name = "message_log"
required-features = ["client"]

[[example]]
name = "cmd_bot"
required-features = ["client"]

[package.metadata.nix]
build = true
library = true

[workspace.metadata.nix]
systems = ["x86_64-linux"]
