name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-compile:
    runs-on: ubuntu-latest
    steps:
    - name: Get Date
      id: get-date
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
      shell: bash
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ steps.get-data.outputs.date }}-${{ hashFiles('Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-
    - uses: actions/checkout@v2
    - uses: textbook/git-checkout-submodule-action@master
    - name: Install deps
      run: |
        sudo apt update -yy
        sudo apt install -yy --no-install-recommends protobuf-compiler protobuf-compiler-grpc
        rustup component add clippy
    - name: Check
      run: cargo check --verbose
    - name: Clippy
      uses: actions-rs/clippy-check@v1.0.7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: cargo build --verbose
