name: Rust

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - '*.nix'
      - 'flake.lock'
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master

    - name: Install dependencies
      run: |
        sudo apt update -yy
        sudo apt install -yy --no-install-recommends protobuf-compiler protobuf-compiler-grpc
    - name: Install rust
      run: rustup default stable && rustup update

    - name: Cache Rust artifacts
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ./target
        key: cargo-${{ runner.os }}-${{ github.sha }}
        restore-keys: cargo-${{ runner.os }}-
        
    - name: Check
      run: cargo check --all-targets --all-features --verbose
    - name: Clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-targets --all-features

    - name: Build
      run: cargo build --all-targets --all-features --verbose

    - name: Test
      run: RUST_LOG=info cargo test --all-features --verbose
    
    - name: Doc
      run: cargo doc --no-deps --all-features --verbose

    - name: Finalize documentation
      run: |
        CRATE_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]' | cut -f2 -d"/")
        echo "<meta http-equiv=\"refresh\" content=\"0; url=${CRATE_NAME/-/_}\">" > target/doc/index.html
        touch target/doc/.nojekyll

    - name: Publish docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: target/doc/
        publish_branch: gh-pages