name: Rust

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - '**/*.nix'
      - 'nix/envrc'
      - 'flake.lock'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - '**/*.nix'
      - 'nix/envrc'
      - 'flake.lock'

env:
  CARGO_TERM_COLOR: always
  TESTER_PASSWORD: ${{ secrets.TESTER_PASSWORD }}

jobs:
  all:
    strategy:
      matrix:
        rust: ['1.51.0', '1.52.1']
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master

    - name: Install dependencies
      run: |
        sudo apt update -yy
        sudo apt install -yy --no-install-recommends protobuf-compiler
    - name: Install rust
      run: rustup default ${{ matrix.rust }} && rustup component add rustfmt clippy

    - name: Cache rust
      uses: Swatinem/rust-cache@v1

    - name: Clippy default features
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-targets
        name: "clippy(${{ matrix.rust }}): default"
    
    - name: Clippy default + client features
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-targets --features client
        name: "clippy(${{ matrix.rust }}): default + client"

    - name: Clippy default + client + request_method features
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-targets --features client,request_method
        name: "clippy(${{ matrix.rust }}): default + client + request_method"

    - name: Clippy all features
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-targets --all-features
        name: "clippy(${{ matrix.rust }}): all"

    - name: Build default features
      run: cargo build --all-targets --verbose
    - name: Build client feature
      run: cargo build --all-targets --features client --verbose
    - name: Build client request_method features
      run: cargo build --all-targets --features client,request_method --verbose
    - name: Build all features
      run: cargo build --all-targets --all-features --verbose

    - name: Build default features
      run: RUST_LOG=debug cargo test --verbose
    - name: Build client feature
      run: RUST_LOG=debug cargo test --features client --verbose
    - name: Build client request_method features
      run: RUST_LOG=debug cargo test --features client,request_method --verbose
    - name: Build all features
      run: RUST_LOG=debug cargo test --all-features --verbose

    - name: Doc
      if: ${{ matrix.rust == '1.52.1' }}
      run: cargo doc --no-deps --all-features --verbose

    - name: Finalize documentation
      if: ${{ matrix.rust == '1.52.1' }}
      run: |
        CRATE_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]' | cut -f2 -d"/")
        echo "<meta http-equiv=\"refresh\" content=\"0; url=${CRATE_NAME/-/_}\">" > target/doc/index.html
        touch target/doc/.nojekyll

    - name: Publish docs
      if: ${{ github.event_name == 'push' && matrix.rust == '1.52.1' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: target/doc/
        publish_branch: gh-pages