name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/checkout@v2
    - uses: textbook/git-checkout-submodule-action@master
    - name: Add protobuf
      run: sudo apt update -yy && sudo apt install -yy --no-install-recommends protobuf-compiler protobuf-compiler-grpc
      
    - name: Check
      run: cargo check --verbose
    - name: Build
      run: cargo build --verbose
    - name: Check use_parking_lot feature
      run: cargo check --verbose --features use_parking_lot
    - name: Build use_parking_lot feature
      run: cargo build --verbose --features use_parking_lot
