name: Rust

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - '**/*.nix'
      - 'nix/envrc'
      - 'flake.lock'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - '**/*.nix'
      - 'nix/envrc'
      - 'flake.lock'

env:
  CARGO_TERM_COLOR: always

jobs:
  all:
    strategy:
      matrix:
        rust: ['1.58.1', '1.57.0']
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install dependencies
      run: |
        sudo apt update -yy
        sudo apt install -yy --no-install-recommends protobuf-compiler
    - name: Install rust
      run: |
        rustup default ${{ matrix.rust }} && rustup component add rustfmt clippy
        rustup target add wasm32-unknown-unknown

    - name: Cache rust
      uses: Swatinem/rust-cache@v1

    - name: Clippy default features
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-targets
        name: "clippy(${{ matrix.rust }}): default"

    - name: Clippy stable protocols
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-targets --features gen_stable_protocols
        name: "clippy(${{ matrix.rust }}): default"

    - name: Clippy staging protocols
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-targets --features gen_staging_protocols
        name: "clippy(${{ matrix.rust }}): default"

    - name: Clippy all protocols
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-targets --features gen_all_protocols
        name: "clippy(${{ matrix.rust }}): default"

    - name: Clippy default + client_native features
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-targets --features client_native
        name: "clippy(${{ matrix.rust }}): default + client_native"

    - name: Clippy default + client_native + client_backoff features
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-targets --features client_native,client_backoff
        name: "clippy(${{ matrix.rust }}): default + client_native + client_backoff"

    - name: Clippy default + client_web features
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --target wasm32-unknown-unknown --package harmony_rust_sdk --features client_web
        name: "clippy(${{ matrix.rust }}): default + client_web"

    - name: Clippy default + client_web + client_backoff features
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --target wasm32-unknown-unknown --package harmony_rust_sdk --features client_web,client_backoff
        name: "clippy(${{ matrix.rust }}): default + client_web + client_backoff"

    - name: Test client_native
      run: RUST_LOG=debug cargo test --all-targets --features client_native

    - name: Test all protocols
      run: RUST_LOG=debug cargo test --all-targets --features gen_all_protocols

    - name: Doc
      if: ${{ matrix.rust == '1.58.1' }}
      run: cargo doc --no-deps --features client_native,gen_all_protocols --verbose

    - name: Finalize documentation
      if: ${{ github.ref == 'refs/heads/master' && matrix.rust == '1.58.1' && github.event_name == 'push' }}
      run: |
        CRATE_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]' | cut -f2 -d"/")
        echo "<meta http-equiv=\"refresh\" content=\"0; url=${CRATE_NAME/-/_}\">" > target/doc/index.html
        touch target/doc/.nojekyll

    - name: Publish docs
      if: ${{ github.ref == 'refs/heads/master' && matrix.rust == '1.58.1' && github.event_name == 'push' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: target/doc/
        publish_branch: gh-pages

    - name: Trigger integration testing
      if: ${{ github.ref == 'refs/heads/master' && matrix.rust == '1.58.1' && github.event_name == 'push' }}
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.INTEGRATION_TEST_PAT }}
        repository: harmony-development/integration-testing
        event-type: dep-updated