name: Rust

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - '*.nix'
      - 'flake.lock'
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Common actions
      uses: ./
        
    - name: Check
      run: cargo check --all-targets --features client,gen_server --verbose
    - name: Clippy
      uses: actions-rs/clippy-check@v1.0.7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-targets --features client,gen_server

  compile:
    needs: check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Common actions
      uses: ./

    - name: Doc
      run: cargo doc --features client,gen_server --verbose
    - name: Build
      run: cargo build --all-targets --features client,gen_server --verbose

  tests:
    needs: compile
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Common actions
      uses: ./

    - name: Test
      run: cargo test --features client,gen_server --verbose --no-fail-fast
